# Generated by Django 3.2.16 on 2025-04-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20250425_0600'),
        ('posts', '0004_auto_20250227_0408'),
    ]

    operations = [
    ]
